#!/bin/bash
set -e
((EUID==0)) || { echo "run as root"; exit 1; }

BBOX="${1:-$(which busybox)}"
TMP=$(mktemp -d /tmp/container-XXXX)
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP/bin"
mkdir -p "$TMP/sbin"
mkdir -p "$TMP/etc"
cp $BBOX "$TMP/bin/busybox"
"$TMP/bin/busybox" --install "$TMP/bin"
"$TMP/bin/busybox" --install "$TMP/sbin"
touch "$TMP/etc/os-release"
echo '::respawn:/sbin/getty -L pts/0 115200 linux' > "$TMP/etc/inittab"
echo "root:x:0:0:root:/root:/bin/sh" > "$TMP/etc/passwd"
echo "root::0:0:99999:7:::"  > "$TMP/etc/shadow"
mkdir "$TMP/root"
systemd-nspawn -D "$TMP" --boot
